# Generated by Django 2.2.6 on 2019-10-25 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Sport', 'Sport'), ('Cinema', 'Cinema'), ('Economie', 'Economie'), ('Politique', 'Politique'), ('Automobile', 'Automobile'), ('Hightech', 'Hightech'), ('Musique', 'Musique'), ('Divertissement', 'Divertissement'), ('Voyage', 'Voyage')], max_length=30)),
                ('description', models.TextField()),
                ('etiquette', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/contenu/%Y/%m/%d/')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Contenu',
                'verbose_name_plural': 'Contenus',
            },
        ),
    ]
